### PR TITLE
Fixes #1009

### LINKED ISSUE #1009: ChefSpec does not automatically install cookbooks from chef server when using Policyfile.rb
## Description

When configuring chefspec with a policyfile it does not automatically pull down cookbooks.

```ruby
# spec/spec_helper.rb
require 'chefspec'
require 'chefspec/policyfile'

CookbookOmnifetch.configure do |config|
  config.default_chef_server_http_client = ChefCLI::ChefServerAPIMulti.new("https://chef-server.domain.com/organizations/my_org", {})
end
```

When executing rspec I get an error

```
$ chef exec rspec
```

```text
An error occurred in a `before(:suite)` hook.
Failure/Error: raise PolicyfileInstallError.new("Failed to generate Policyfile.lock", error)
ChefCLI::PolicyfileInstallError:
  Failed to generate Policyfile.lock
# /home/jason.barnett/.chefdk/gem/ruby/2.7.0/gems/chef-cli-4.0.0/lib/chef-cli/policyfile_services/install.rb:117:in `rescue in generate_lock_and_install'
# /home/jason.barnett/.chefdk/gem/ruby/2.7.0/gems/chef-cli-4.0.0/lib/chef-cli/policyfile_services/install.rb:96:in `generate_lock_and_install'
# /home/jason.barnett/.chefdk/gem/ruby/2.7.0/gems/chef-cli-4.0.0/lib/chef-cli/policyfile_services/install.rb:65:in `run'
# ------------------
# --- Caused by: ---
# NoMethodError:
#   undefined method `client_key' for nil:NilClass
#   /home/jason.barnett/.chefdk/gem/ruby/2.7.0/gems/chef-cli-4.0.0/lib/chef-cli/policyfile/chef_server_cookbook_source.rb:89:in `http_connection_for'
Finished in 0.04965 seconds (files took 1.23 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

## Workaround

Run `chef install` before running `chef exec rspec`.

## What should happen

Chefspec should automatically install any dependencies from Chef Server assuming someone has a `~/.chef/config.rb`, etc.

### PR DESCRIPTION
**Pull request by jasonwbarnett**
I wish I could tell you why this works, but I can't. I largely poked around the `chef-cli` and blindly copied the patterns from there. I was mainly comparing the differences between chefspec's use of the `PolicyfileServices::Install` class and chef-cli during the `chef install`/`chef update` commands. It seemed pretty clear based on the exception and the code that it was missing the chef config.

References:

- https://github.com/chef/chef-cli/blob/master/lib/chef-cli/configurable.rb#L50-L65

### CODE REVIEW

File: lib/chefspec/policyfile.rb [hunk 1]
```diff
@@ -27,9 +27,12 @@ def setup!
         policyfile_path = File.join(Dir.pwd, "Policyfile.rb")
       end
 
+      Chef::WorkstationConfigLoader.new(nil).load
```
Comment (jasonwbarnett) [inline lib/chefspec/policyfile.rb:30]: I suppose this could be configurable through some rspec configuration, but I just added the bare minimum that gets it working by hunting and finding the default locations.

**Comment by jasonwbarnett** [comment]
I started to do some more thinking and I'm scratching my head, why does the [ChefServerCookbookSource][0] class have the `:chef_config` as an optional parameter? I'm curious, under what conditions would you ever use a chef server cookbook source WITHOUT a chef config (aka auth)? I'm not sure why this class was originally written so this is optional. That seems to be a design break, but I don't really know because I am missing a lot of context, I'm sure.

[0]: https://github.com/chef/chef-cli/blob/master/lib/chef-cli/policyfile/chef_server_cookbook_source.rb#L30

**Comment by lamont-granquist** [comment]
i haven't looked, but i suspect the point of that is to try to use some dependency injection so you can mock Chef::Config in specs (at the very least) without scribbling all over global state.
